# Generated by Django 3.1.6 on 2021-02-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="last_login",
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_request",
            field=models.DateTimeField(null=True),
        ),
    ]
